import Head from "next/head";
import { useState } from "react";
import Navbar from "../components/shared/Navbar";
import Masthead from "../components/main/Masthead";
import { useAppContext } from "../components/context/AppContext";
import Projects from "../components/main/Projects";
import Achievments from "../components/main/Achievements";
import Blogs from "../components/main/Blogs";
import Skills from "../components/main/Skills";
import ContactMe from "../components/main/ContactMe";

export default function Home() {
  const mycontext = useAppContext();
  const { isOpen } = mycontext;
  const components = [
    <Masthead />,
    <Projects />,
    <Blogs />,
    <Skills />,
    <Achievments />,
    <ContactMe />,
  ];
  return (
    <div>
      <Head>
        <title>Devstardude</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="left-0 top-0 z-40 fixed">
        <Navbar />
      </div>
      <main
        className={`${
          isOpen ? "navOpen" : "navClose"
        } transition-all duration-500 h-full prose prose-stone dark:prose-invert md:prose-xl lg:prose-2xl max-w-none px-5 md:px-10 lg:pl-1 pb-10`}
      >
        {components.map((i, ind) => (
          <section key={i} id={`section-${ind + 1}`}>
            {i}
          </section>
        ))}
      </main>
    </div>
  );
}
