import Head from "next/head";
import { useState } from "react";
import Navbar from "../components/shared/Navbar";
import Masthead from "../components/main/Masthead";
import { useAppContext } from "../components/context/AppContext";

export default function Home() {
  const mycontext = useAppContext();
  const { isOpen } = mycontext;
  const components = [<Masthead />];
  return (
    <div>
      <Head>
        <title>Devstardude</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="left-0 top-0 z-40 fixed">
        <Navbar />
      </div>
      <main
        className={`${
          isOpen ? "navOpen" : "navClose"
        } transition-all duration-500 h-full`}
      >
        {components.map((i) => (
          <section key={i} id={`section-${i}`}>
            {i}
          </section>
        ))}
      </main>
    </div>
  );
}
